kind: Secret
apiVersion: v1
metadata:
  name: api-db-secret
data:
  username: c29zdHJhZGVz
  password: c29zdHJhZGVz
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: log-db-secret
data:
  password: c29zdHJhZGVzX3Byb2R1Y3Rpb25fbG9n
  username: c29zdHJhZGVzX3Byb2R1Y3Rpb25fbG9n
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: api-sostrades-api-db-data
  namespace: sostrades
data:
  password: YWRtaW4=
  username: c29zdHJhZGVz
type: Opaque
---

kind: Secret
apiVersion: v1
metadata:
  name: api-sostrades-api-db-log
  namespace: sostrades
data:
  password: YWRtaW4=
  username: c29zdHJhZGVz
type: Opaque


---

kind: Secret
apiVersion: v1
metadata:
  name: api-sostrades-api-rsa-key
  namespace: sostrades
data:
  private_key.pem: ''
  public_key.pem: ''
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: githuboauth
  namespace: sostrades
data:
  settings.json: >-
    ewogICAgIkdJVEhVQl9DTElFTlRfSUQiOiAiY2ZjOWVjZjc2MmQ2NjhkYWM0MWQiLAogICAgIkdJVEhVQl9DTElFTlRfU0VDUkVUIjogIjk3NzFjMzRiYzAyNzZkNDNlYzIwOWI5ZWM5NDk1ZDNmZTA3NjRhYTQiLAogICAgIkdJVEhVQl9BUElfVVJMIjogImh0dHBzOi8vYXBpLmdpdGh1Yi5jb20vIiwKICAgICJHSVRIVUJfQVVUSF9VUkwiOiAiaHR0cHM6Ly9naXRodWIuY29tL2xvZ2luL29hdXRoLyIKfQ==

type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: mysql-sostrades-password
  namespace: sostrades
data:
  mysql-password: YWRtaW4=
  mysql-root-password: YWRtaW4=
type: Opaque

---
