kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-integration-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  volumeMode: Filesystem
  
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sostrades-api-data-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem  

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-sostrades-pv
spec:
  capacity:
    storage: 3Gi
  hostPath:
    path: /mnt/data
    type: ''
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  volumeMode: Filesystem
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sostrades-api-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-sostrades-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
  
