kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: sostrades
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: sostrades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: frontend
        deploymentconfig: frontend
    spec:
      volumes:
        - name: default-conf
          configMap:
            name: frontend-sostrades-frontend-config
            items:
              - key: default.conf
                path: default.conf
            defaultMode: 420
      containers:
        - name: frontend
          image: >-
            docker.io/library/frontend:1
          resources:
            limits:
              cpu: 800m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: default-conf
              readOnly: true
              mountPath: /etc/nginx/conf.d/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      restartPolicy: Always          
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
